version: ~> 1.0
jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      services: xvfb
    - os: osx
      compiler: clang
      osx_image: xcode11.3

language : cpp

env:

git:
  submodules: true
  depth: false

before_install:
    #This PPA has all the QT versions, just update it to change versions
    #Full list here: https://launchpad.net/~beineri
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:beineri/opt-qt-5.14.2-bionic; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y update; fi
    #- if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install qt514-meta-minimal; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install qt514svg; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install qt514quickcontrols; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install qt514quickcontrols2; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install qt514graphicaleffects; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install qt514script; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install qt514imageformats; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install libgl1-mesa-glx; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install libgl1-mesa-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then git clone https://github.com/qbs/qbs.git; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd qbs; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then git checkout v1.17.0; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then /opt/qt514/bin/qmake -r qbs.pro && make -j `nproc`; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo make install; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd ..; fi

    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ls -l /usr/lib/x86_64-linux-gnu/libGL.*; fi

    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qt5; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install qbs; fi

    - qbs --version
    - qbs setup-toolchains --detect
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then qbs setup-qt /opt/qt514/bin/qmake qt5; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then qbs setup-qt /usr/local/Cellar/qt/5.14.1/bin/qmake qt5; fi
    - qbs config --list profiles
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then qbs config profiles.qt5.baseProfile x86_64-linux-gnu-gcc-7; fi
    - qbs config defaultProfile qt5

script:
    - echo $TARGET_NAME
    - ulimit -c unlimited
    - ulimit -a

#    - qbs setup-toolchains --detect
#    - qbs setup-qt /opt/qt514/bin/qmake qt5
#    - qbs config profiles.qt5.baseProfile x86_64-linux-gnu-gcc-7
#    - qbs config defaultProfile qt5

    - qbs resolve profile:qt5 config:release
    - qbs build --products CaveWhere profile:qt5 config:debug
    - export LSAN_OPTIONS=suppressions=suppressedLeaks.txt
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then qbs run --products cavewhere-test profile:qt5 config:debug; fi
