# Conan build-environment PATH prepend helper for CaveWhere.
#
# Exposes:
#
#   cw_prepend_conan_buildenv_path()
#       Detects the Conan-generated build-env script (Windows .bat or
#       cross-compile .sh) and prepends its bin directory to PATH +
#       CMAKE_PROGRAM_PATH so native build tools (protoc, etc.) are
#       found before any find_package() that needs them.
#
#       On mobile (iOS/Android), also wires the Conan-deps directory
#       into CMAKE_MODULE_PATH / CMAKE_PREFIX_PATH and seeds <pkg>_DIR
#       cache entries for each Conan-generated *Config.cmake so
#       find_package(... CONFIG) resolves correctly under cross-compile
#       find-root modes.
#
# MUST be called before any find_package() that needs Conan packages
# (absl, protobuf, libssh2, etc.).

# Prefer Conan *build* tools (e.g., native protoc) over system versions.
# On Windows, Qt Creator's auto-setup generates conanbuildenv-<config>-x86_64.bat.
# On cross-compilation (iOS/Android), we parse conanbuild.sh from the conan_deps folder.
function(cw_prepend_conan_buildenv_path)
    if(WIN32)
        if(DEFINED CMAKE_BUILD_TYPE AND NOT CMAKE_BUILD_TYPE STREQUAL "")
            string(TOLOWER "${CMAKE_BUILD_TYPE}" _cw_build_type_lower)
        else()
            set(_cw_build_type_lower "debug")
        endif()

        set(_cw_conan_buildenv
            "${CMAKE_BINARY_DIR}/conan-dependencies/build/conan/conanbuildenv-${_cw_build_type_lower}-x86_64.bat")
        if(NOT EXISTS "${_cw_conan_buildenv}")
            return()
        endif()

        file(STRINGS "${_cw_conan_buildenv}" _cw_path_lines REGEX "^set \"PATH=.*\"$")
        if(NOT _cw_path_lines)
            return()
        endif()

        list(GET _cw_path_lines 0 _cw_path_line)
        string(REGEX REPLACE "^set \"PATH=([^;]+);%PATH%\".*" "\\1" _cw_conan_bin "${_cw_path_line}")
        if(_cw_conan_bin AND EXISTS "${_cw_conan_bin}")
            set(ENV{PATH} "${_cw_conan_bin};$ENV{PATH}")
            list(PREPEND CMAKE_PROGRAM_PATH "${_cw_conan_bin}")
            set(CMAKE_PROGRAM_PATH "${CMAKE_PROGRAM_PATH}" PARENT_SCOPE)
            message(STATUS "CaveWhere: Prepending Conan build-tools bin to PATH: ${_cw_conan_bin}")
        endif()
    elseif(CW_MOBILE)
        # For cross-compilation (iOS/Android), parse the conanbuild.sh generated by Conan
        # to find native build tools (protoc, etc.) and add them to CMAKE_PROGRAM_PATH.
        file(GLOB _cw_conanbuildenv_scripts "${CMAKE_BINARY_DIR}/conan_deps/conanbuildenv-*.sh")
        foreach(_cw_script IN LISTS _cw_conanbuildenv_scripts)
            file(STRINGS "${_cw_script}" _cw_path_lines REGEX "^export PATH=")
            foreach(_cw_line IN LISTS _cw_path_lines)
                # Extract the path value between quotes: export PATH="dirs:$PATH"
                string(REGEX REPLACE "^export PATH=\"([^\"]+)\".*" "\\1" _cw_path_value "${_cw_line}")
                # Remove the trailing :$PATH
                string(REGEX REPLACE ":\\$PATH$" "" _cw_path_value "${_cw_path_value}")
                # Split on colons
                string(REPLACE ":" ";" _cw_path_dirs "${_cw_path_value}")
                foreach(_cw_dir IN LISTS _cw_path_dirs)
                    if(IS_DIRECTORY "${_cw_dir}")
                        list(APPEND CMAKE_PROGRAM_PATH "${_cw_dir}")
                        set(ENV{PATH} "${_cw_dir}:$ENV{PATH}")
                        message(STATUS "CaveWhere: Prepending Conan build-tools bin to PATH: ${_cw_dir}")
                    endif()
                endforeach()
            endforeach()
        endforeach()

        # Set up Conan deps directory for find_package resolution.
        # We add it to CMAKE_MODULE_PATH (for Find*.cmake modules like FindProtobuf.cmake),
        # CMAKE_PREFIX_PATH (for *Config.cmake files), and set explicit <pkg>_DIR cache entries
        # to prevent find_package from picking up stale configs in Conan build directories.
        # Note: we do NOT change CMAKE_FIND_ROOT_PATH_MODE_* because setting them to BOTH
        # breaks Qt's own dependency resolution (e.g., GLESv2 on iOS).
        set(_cw_conan_deps_dir "${CMAKE_BINARY_DIR}/conan_deps")
        if(IS_DIRECTORY "${_cw_conan_deps_dir}")
            list(PREPEND CMAKE_MODULE_PATH "${_cw_conan_deps_dir}")
            list(PREPEND CMAKE_PREFIX_PATH "${_cw_conan_deps_dir}")
            message(STATUS "CaveWhere: Prepending Conan deps to CMAKE_MODULE_PATH and CMAKE_PREFIX_PATH: ${_cw_conan_deps_dir}")

            # Cross-compilation toolchains (Android NDK, Qt-for-iOS) set
            # CMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY, which blocks the
            # CMAKE_PREFIX_PATH fallback. Putting conan_deps on
            # CMAKE_FIND_ROOT_PATH makes find_package() discover configs
            # there even under that mode, and filename search is
            # case-insensitive so `find_package(PROJ)` resolves
            # `proj-config.cmake` without needing a case-matched
            # <pkg>_DIR entry.
            if(ANDROID OR CW_MOBILE)
                list(PREPEND CMAKE_FIND_ROOT_PATH "${_cw_conan_deps_dir}")
            endif()

            # Set <package>_DIR for Conan packages so config-mode find_package
            # uses the correct Conan-generated *Config.cmake instead of stale build-dir configs.
            # On iOS, ZLIB comes from the SDK and overriding ZLIB_DIR breaks
            # Qt's internal ZLIB usage. On Android the NDK ships libz.so but
            # no ZLIBConfig.cmake, so Conan's ZLIBConfig is the only way to
            # satisfy OpenSSLConfig's find_dependency(ZLIB CONFIG REQUIRED).
            set(_cw_skip_dir_packages "")
            if(APPLE)
                list(APPEND _cw_skip_dir_packages "ZLIB")
            endif()
            file(GLOB _cw_conan_configs "${_cw_conan_deps_dir}/*[Cc]onfig.cmake")
            foreach(_cw_cfg IN LISTS _cw_conan_configs)
                get_filename_component(_cw_cfg_name "${_cw_cfg}" NAME_WE)
                # Conan generates both PascalCase (BZip2Config.cmake → BZip2) and
                # kebab-lowercase (absl-config.cmake → absl) config names; strip
                # either tail so <pkg>_DIR matches the find_package() package
                # name. Needed on Android because the NDK toolchain sets
                # CMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY, which suppresses the
                # CMAKE_PREFIX_PATH fallback and makes <pkg>_DIR the only route.
                string(REGEX REPLACE "-?[Cc]onfig$" "" _cw_pkg_name "${_cw_cfg_name}")
                if(NOT "${_cw_pkg_name}" IN_LIST _cw_skip_dir_packages)
                    set(${_cw_pkg_name}_DIR "${_cw_conan_deps_dir}" CACHE PATH "Conan ${_cw_pkg_name} dir" FORCE)
                    message(STATUS "CaveWhere: Setting ${_cw_pkg_name}_DIR = ${_cw_conan_deps_dir}")
                endif()
            endforeach()
        endif()

        set(CMAKE_PROGRAM_PATH "${CMAKE_PROGRAM_PATH}" PARENT_SCOPE)
        set(CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH}" PARENT_SCOPE)
        set(CMAKE_PREFIX_PATH "${CMAKE_PREFIX_PATH}" PARENT_SCOPE)
        set(CMAKE_FIND_ROOT_PATH "${CMAKE_FIND_ROOT_PATH}" PARENT_SCOPE)
    endif()
endfunction()
