name: Build on Linux

on:
  push:
    branches:
      - WIP-qt6
  pull_request:
    branches:
      - '*'

jobs:
  build:
    #CaveWhere orginization
    #runs-on: CaveWhereRunner
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 #Fetch the tags for the versions to work correctly

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            pipx \
            liblocale-po-perl \
            git

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: '==3.1.*'
          version: '6.8.0'
          host: 'linux'
          target: 'desktop'
          arch: 'linux_gcc_64'
          modules: 'qtshadertools'

      - name: Installing Conan
        run: |
            pipx install conan

      - name: Check Conan Version
        run: conan --version

      - name: Configure Conan Profile
        run: |
          conan profile detect --force

      - name: Cache Conan Packages
        id: cache-conan
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.*') }}
          restore-keys: |
            ${{ runner.os }}-conan-

      # - name: Set up cache for apt packages
      #   uses: actions/cache@v4
      #   with:
      #     path: /var/cache/apt/archives
      #     key: ${{ runner.os }}-apt-${{ hashFiles('conanfile.*') }}
      #     restore-keys: |
      #       ${{ runner.os }}-apt-

      #conan install . --build=missing -o CaveWhere/*:system_qt=False --output-folder=build \

      - name: Install Dependencies with Conan
        run: |
            conan install . --build=missing --output-folder=build \
            -s compiler.cppstd=17 \
            -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True

      - name: ls build dir
        run: |
            ls -la ${{ github.workspace }}/build
            ls -la ${{ github.workspace }}/build/${{ github.workspace }}/build


      - name: Configure the Project with CMake
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_PDF=OFF \
          -DCMAKE_PREFIX_PATH=${{ github.workspace }}/Qt/6.8.0/gcc_64/lib \
          -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake -S . -B build

      # - name: Build the Project
      #   run: cmake --build build
