name: Build on Linux

on:
  push:
    branches:
      - WIP-qt6
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: CaveWhereRunner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            pipx

      - name: Installing Conan
        run: |
            pipx install conan

      - name: Check Conan Version
        run: conan --version

      - name: Configure Conan Profile
        run: |
          conan profile detect --force

      - name: Cache Conan Packages
        id: cache-conan
        uses: actions/cache@v4
        with:
          path: ~/.conan2
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.*') }}
          restore-keys: |
            ${{ runner.os }}-conan-

      # - name: Set up cache for apt packages
      #   uses: actions/cache@v4
      #   with:
      #     path: /var/cache/apt/archives
      #     key: ${{ runner.os }}-apt-${{ hashFiles('conanfile.*') }}
      #     restore-keys: |
      #       ${{ runner.os }}-apt-

      - name: Install Dependencies with Conan
        run: |
            conan install . --build=missing -o CaveWhere/*:system_qt=False --output-folder=build \
            -s compiler.cppstd=17 \
            -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True


      # - name: Configure the Project with CMake
      #   run: |
      #     cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DWITH_PDF=OFF \
      #     -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake -S . -B build

      # - name: Build the Project
      #   run: cmake --build build
